### PR TITLE
MODGQL-127 Setup cors middleware

### PR DESCRIPTION
**Pull request by mkuklis**
Without this @zburke ran into an issue yesterday:

https://folio-project.slack.com/archives/CAN13SWBF/p1600971969003200

I tried locally and I was also able to repro the same issue.

This cors flag seems to work here.

[MODGQL-127](https://issues.folio.org/browse/MODGQL-127)

### CODE REVIEW

**Comment by zburke** [comment]
@mkuklis, how did this jive with @MikeTaylor's comment on the ticket? It looks like you two took opposite approaches (he turned it off, but you turned it on). 

> I am now explicitly passing the `cors: false` option in ApolloServer constructor's option block. It makes no difference — we are still getting the blasted header.

Is the issue that we need CORS enabled so its headers are correctly passed through, whereas if the middleware is absent/turned off but the `origin` header is present in the incoming request, this causes the headers to be duplicated instead of coalesced?

Also, wow, nice sleuthing! 🕵️

**Review by MikeTaylor — COMMENTED** [review]
If this works, then _great_! Does it?

BTW., I appreciate adding the new environment variables as well — that's worth doing — but could you please save that for a separate commit, which also includes appropriate updates to the documentation?

**Comment by MikeTaylor** [comment]
I tried manually applying the relevant part of this PR (the `cors: true` bit) and it did not solve the problem — I am still seeing the ACAO header.

**Comment by MikeTaylor** [comment]
… but changing it to `cors: false` _does_ work!

@mkuklis have you done a Dumb Commit? :-)

**Comment by MikeTaylor** [comment]
OK, I am going to ignore this PR and manually apply the fix in the form that works.

When you have time, please make a new one that does the environment-variable stuff.

**Comment by MikeTaylor** [comment]
Done and fixed in https://github.com/folio-org/mod-graphql/commit/1a346f617ac60d9fd6ccada2c24093490c781c5b — many thanks to @mkuklis for making the hard yards.

**Comment by mkuklis** [comment]
Glad the `cors: false` works. I was seeing a different behavior here when running it locally with a remote okapi.

It looks like `cors: false` completely turns it off:

https://github.com/apollographql/apollo-server/blob/main/packages/apollo-server-express/src/ApolloServer.ts#L174-L178

I will give it a try now.

**Pull request closed without merging**
