### PR TITLE
MODGQL-150: Use multi-stage build to reduce Docker image size

### PR DESCRIPTION
**Pull request by julianladisch**
This reduces the Docker images size from 428 MB to 213 MB.

### CODE REVIEW

**Comment by skomorokh** [comment]
Thanks Julian, I actually agreed with you though and was fine with the other change. I don't know that it's worth keeping the extra layer since it looks like it's adding a lot of space to the image? Since you found better documentation for the comment maybe leave that in there with the commands commented out just in case someone wants to re-use it like that but I think for the way this container will be used there's more benefit to be had in making it less than half the size?

Also, as mentioned, I believe that ./tests/setup.sh doesn't depend on the dev dependencies at the top level so the first yarn install (without the --production) is unnecessary? But @MikeTaylor will need to confirm as I'm not 100% on how that all works, just that I suspect it's in no way a test and instead invokes a script to generate schemas.

**Comment by julianladisch** [comment]
> ./tests/setup.sh doesn't depend on the dev dependencies

Thank you for this information, I saw the directory name `test` and thought that it requires the test dependencies.

I've removed the test layer and the test dependencies.

The production layer is still needed to remove the yarn cache files.

**Comment by MikeTaylor** [comment]
Jason is right -- the "test" script is misnamed for historical reasons, and does not need testing dependencies.

**Comment by julianladisch** [comment]
I've completely removed testing dependencies from the build.

**Review by skomorokh — APPROVED** [review]
Thanks for your patience and for improving this!

**Comment by MikeTaylor** [comment]
Sorry I lost track of this, I thought we'd finished.

Honestly, I am not familiar enough with Jenkins to have much of an opinion on this. But given that (A) it obviously works, as evidenced by the passed tests, and (B) it makes the image smaller, that's good enough for me.

Thanks for making this happen.

**Pull request merged**
